<?php 
/**
 * Implements hook_help
 * 
 * Displays help and module information
 * @param path
 * 	Which path of the site we're using to display help
 * @param arg
 * 	Array that holds the current path as returned from the arg() function
 */
function current_students_help($path, $arg) {
	switch ($path) {
		case "admin/help#current_students":
			return '<p>' . t("Imports institutional student data into the Writing Center modules.") . '</p>';
			break;
	}
}

/**
 * Implements hook_clock_info()
 */
function current_students_block_info() {
	$blocks['current_students'] = array(
		//The name that will appear in the block list.
		'info' => t('Current Students active'),
		// default setting
		'cache'=> DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}

/**
 * Implements hook_user_login
 * 1. First checks for the account information and attempts to match the account information with current_student data
 * 2. If the student data exists and hasn't recently been imported into yc_patron, then import/update the information
 * 3. If the student data exists, then set the student role
 * 
 */
function current_students_user_login(&$edit, $account) {
	global $user;
	//
}